### ISSUE TITLE
Bruker datasets (not timsTOF) fail

### ISSUE THREAD

**Issue by p-bell** [Nesvilab/IonQuant#37]
Hi,

I'm trying to analyse data acquired with a Bruker Impact II, but IonQuant fails.

The logs (attached) cite an invalid path directory for Bruker data - however, the original .d folder and the .mzml (generated by msconvert and used for the search) are both there in the folder.

I also notice in the logs that IonQuant assumes that any .d folder is timsTOF data, and overrides the ionmobility parameter from 0 to 1.

Could this be a source of the problem? / is it possible to analyse non-timsTOF Bruker datasets? 

Thanks and best wishes,
Pete

[log_2023-01-25_09-43-52.txt](https://github.com/Nesvilab/IonQuant/files/10502199/log_2023-01-25_09-43-52.txt)

**Comment by fcyu** [comment]
Hi Pete,

Yes, IonQuant will use `.d` if there are both `.d` and `.mzML` because it contains more information and is more accurate. It will also assume that the .d is from timsTOF. If your data is not from timsTOF, you need to remove the .d to make sure that IonQuant loads the mzML file.

Best,

Fengchao

**Comment by p-bell** [comment]
Thanks Fenchao, that's done the trick! Runs to completion now.

Best wishes,
Pete

**Comment by fcyu** [comment]
Glad to hear that it works. Please feel free to contact us if there is any further questions.

Best,

Fengchao
