### ISSUE TITLE
got an out-of-memory error when running IonQuant

### ISSUE THREAD

**Issue by huiyinc** [Nesvilab/IonQuant#54]
Hi Fengchao,

I am working on proteomics data using FragPipe (with IonQuant) and processing a dataset of 1392 mzML files. The analysis proceeds smoothly until IonQuant runs into an out-of-memory error. My computer has 280 GB of memory, so I am unsure if increasing the memory is the solution. I would appreciate any suggestions you might have. I've attached the log file for your reference.

Thank you.

Huiyin
[log_2024-05-22_14-50-43.txt](https://github.com/Nesvilab/IonQuant/files/15465889/log_2024-05-22_14-50-43.txt)

**Comment by fcyu** [comment]
Hi Huiyin,

Thanks for the feedback. With 1392 files, it might a bit memory-consuming for IonQuant. I have reduced the memory footprint a little bit in the latest version. Could you send an email to yufeATumich.edu (replace `AT` with `@`) so that I can share the pre-released version to you?

Thanks,

Fengchao

**Comment by huiyinc** [comment]
﻿Hi Fengchao,

Thanks for the prompt reply. I will send the email.

Best wishes,

Huiyin
